### ISSUE TITLE
UI Design Software do Bem

### ISSUE THREAD

**Issue by tuliofaria** [softwaredobem/softwaredobem#2]
It´s important to cover:
- About the project
- At least two languages (PT and EN)
- Project list

**Comment by tuliofaria** [comment]
It´s nice to use Figma for doing this (www.figma.com).

**Comment by AdrianoCahete** [comment]
Hey @tuliofaria 

What do you expect for this UI? What do you need to be displayed?

**Comment by tuliofaria** [comment]
hey @AdrianoCahete ,
thank you for your interest.

For the first version, we should display what is "Software do Bem" (we have some short paragraphs into source-code about it) and list the projects (for now, we have two: Projeto Parabéns and Vai dar Certo).

I think we can start with one page and evolve in future versions.

**Comment by tuliofaria** [comment]
Adding more info: you can find the logo/brand in PNG version https://github.com/softwaredobem/softwaredobem/blob/master/public/software-do-bem-logo.png

**Comment by Victorybrown** [comment]
Are there other screens i can work on

**Comment by tuliofaria** [comment]
Hi @tory-brown , you can work on project details page. What do you think?

**Comment by Victorybrown** [comment]
ok where is the issue, can I be assigned to it

**Comment by Victorybrown** [comment]
what should the project page look like and what do you expect

**Comment by AdrianoCahete** [comment]
@tuliofaria Sorry about the late reply, I'm finishing the idea this weekend.

> we should display what is "Software do Bem" (we have some short paragraphs into source-code about it) 

Didn't found on the source code, but found on internet the following:
"Iniciativa opensource do DevPleno que consiste em um projeto de marketplace para conectar instituições filantrópicas e voluntários."

Is this right or do you have a more detailed one?

**Comment by AdrianoCahete** [comment]
Ok, I had some problems to find the description of both projects too, so I found a page on Facebook for "Projeto Parabéns" and did a freestyle translation based on content, to match the mockup in English:

> This project provides parties for children and teenagers in situations of social vulnerability, who are in shelters, NGOs, communities, and occupations in the city of Sao Paulo (Brazil).

But didn't find anything for the "Vai dar certo" project, so I'm using the same text from the other project (or I may change to a lorem ipsum).

For the Main project, I did a freestyle translation too, but based on your youtube video :)

> Software do Bem is an Open Source initiative that aims to be a marketplace to be the bridge between the philanthropic institutions and the volunteers

I'll push the PR later today (because of hacktoberfest needs).

Edit: to work with Hacktoberfest, you need to add the `hacktoberfest` topic to the repo and label the PR as `hacktoberfest-accepted` or `invalid` if it's the case.

**Comment by tuliofaria** [comment]
Hi @AdrianoCahete ,
thank you for adding your translations. It´s nice to have something to start from.
The blurbs right now are not so important as the design and tech pieces. But the way you wrote works fine and represents the goal of each project.

About the hacktoberfest, gotcha! They changed again - aparently. :/

**Comment by AdrianoCahete** [comment]
If you don't have any fix to do in that mockup I can apply to the project source if you want/need... :)

**Comment by Victorybrown** [comment]
https://www.figma.com/proto/rGoEpchxLkz1McOOeeQJ9E/Untitled?node-id=4%3A2&scaling=scale-down-width


before I push, please can you check if I'm on track, I asked some questions about what you expect, but got no reply.

**Comment by Victorybrown** [comment]
I didn't hear from you
