### ISSUE TITLE
Add CI using GH Actions

### ISSUE THREAD

**Issue by tuliofaria** [softwaredobem/softwaredobem#3]

**Comment by williamtome** [comment]
Hi @tuliofaria. 

I have a question. You need that the pipeline be created to deployment on Vercel? Can you give more details on how this pipeline needs to be done? I want contribute!

Thanks!

**Comment by tuliofaria** [comment]
Hey @williamtome ,
sure.
The objective of the CI is to run the integration tests here in github. It can be done in Vercel as well (but need to be tested as well).
In github, is easier to test and keep the pipeline :)

**Comment by williamtome** [comment]
Ok. Can you assign this task to me?

**Comment by williamtome** [comment]
Hey @tuliofaria 

I'm create the pull request #5 for this issue.

Please, check it form me? Thanks!
